name: Firmware Security Scan

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Scan for dangerous patterns
      run: |
        python3 scanner.py firmware.bin
    - name: Verify checksum
      run: |
        sha256sum firmware.bin > checksum.txt
        grep $(sha256sum firmware.bin | cut -d' ' -f1) allowed_hashes.txt || exit 1
